popm/wasm: add error codes
hemilabs/heminetwork pull request #154
Opened 2024-06-21 15:53 UTC by joshuasing

**Summary**
Add error codes to the WebAssembly PoP Miner.
These error codes will be used to programatically handle errors and display useful information to users.

The default error code is ErrorCodeInternal ("internal").

**Changes**
 - Add `ErrorCode` type and add `Code` field to the existing `Error` type
 - Add `ErrorCodeInternal` for use with internal errors (and is the default error code)
 - Add `ErrorCodeInvalidValue` for use when an invalid value is provided for an argument, currently only used in `generateKey`
 - Refactor how some elements are displayed in integration test web page to help with testing
 - Add `codedError` type, used to include an error code in an error that is extracted when creating an `Error` that will be converted to a JavaScript Object
 
The decision to make error codes strings was made as they are generally easier to compare in JavaScript (and can be unions in TypeScript), and don't require the use of a JavaScript enum. Integers would likely be more preferable in Go, however as these are sent between different programming languages, I believe strings will work better.

More error codes will be added as needed in future pull requests.

2024-06-24 09:18 UTC, marcopeereboom requested changes

2024-06-24 09:18 UTC, marcopeereboom commented on web/popminer/api.go
> +type ErrorCode string
I don't think we should use strings as the key. I feel like an int with a textual representation is a better option. In my experience string compares as error values tends to end in tears.

2024-06-24 12:30 UTC, ClaytonNorthey92 approved these changes

2024-06-24 12:47 UTC, ArturDolzan reviewed
LGTM

2024-06-26 14:18 UTC, marcopeereboom requested changes
We need to make error code 0 "invalid". As in "it means nothing and someone did something wrong in their code" Then error codes that mean something must be != 0.

2024-06-27 14:23 UTC, marcopeereboom approved these changes

2024-06-27 14:29 UTC, merged