all: build with go1.23
hemilabs/heminetwork pull request #217
Opened 2024-08-20 14:29 UTC by joshuasing

**Summary**
Build project with [Go v1.23](https://tip.golang.org/doc/go1.23).
This does not change the `go` directive in the `go.mod` files, meaning we do not require consumers of this module to use `go1.23`, and we cannot use Go v1.23 features yet.

**Changes**
- Use toolchain `go1.23`
- Use Go `1.23.x` in GitHub Actions
- Update Go Docker images to `1.23-alpine3.20` and `1.23-bookworm` (debian)
- Document that Go 1.23 is required for building (previously 1.22.2 or newer)

*Note: Go v1.23 introduces new `go vet` checks for the `slices` package which are currently failing, resolved by #215 *

2024-08-21 14:39 UTC, marcopeereboom approved these changes

2024-08-21 18:49 UTC, jcvernaleo approved these changes
OK

2024-08-21 19:28 UTC, ClaytonNorthey92 commented
@joshuasing as long as this passes this is an approval from me ✅ https://github.com/hemilabs/heminetwork/actions/runs/10496216883

2024-08-21 19:51 UTC, ClaytonNorthey92 requested changes
hey @joshuasing it seems that this breaks localnet tests

https://github.com/hemilabs/heminetwork/actions/runs/10496216883/job/29076358690#step:5:4833

```
90.37 link: github.com/fjl/memsize: invalid reference to runtime.stopTheWorld
90.57 util.go:48: exit status 1
90.57 exit status 1
90.63 make: *** [Makefile:12: geth] Error 1
```

can we fix this before merge? I am happy to look as well

2024-08-22 10:05 UTC, marcopeereboom approved these changes

2024-08-26 16:59 UTC, joshuasing commented
Reverted to Go 1.22.6 in `e2e/optimism-stack.dockerfile` due to an incompatibility between a module used by go-ethereum and Go 1.23 (`github.com/fjl/memsize`). Once we rebase https://github.com/hemilabs/op-geth, we should update this to Go 1.23.

https://github.com/fjl/memsize/issues/4
https://github.com/ethereum/go-ethereum/issues/30100
https://github.com/ethereum/go-ethereum/pull/30253
https://github.com/ethereum-optimism/op-geth/commit/04354cf987b0a9429b3f9262c2dd7f7dc95ad935

2024-08-28 17:40 UTC, ClaytonNorthey92 approved these changes

2024-08-28 17:41 UTC, merged