Add common user-specific files to gitignore
hemilabs/heminetwork pull request #51
Opened 2024-04-05 10:44 UTC by joshuasing

**Summary**
Add common user-specific files to the `.gitignore` file.

**Changes**
 - Add common Vim temporary files to `.gitignore`
 - Add common JetBrains temporary/user-specific files to `.gitignore`
 - Add common Visual Studio Codes temporary/user-specific files to `.gitignore`

2024-04-05 12:30 UTC, jcvernaleo requested changes
If we're going to add those editor files, can we add eamcs *~ files too?

2024-04-05 13:30 UTC, joshuasing commented
> If we're going to add those editor files, can we add eamcs *~ files too?

Sure thing, I will do that now.

2024-04-05 13:37 UTC, jcvernaleo approved these changes
I've been using emacs for over a quarter of a century and those are more random files than even I know about :)

2024-04-08 11:45 UTC, ClaytonNorthey92 approved these changes

2024-04-08 12:44 UTC, merged